security:

    role_hierarchy:
        ROLE_CHEF: ROLE_DEV
        ROLE_COM: ROLE_DEV
        ROLE_ADMIN:
            - ROLE_DEV
            - ROLE_CHEF
            - ROLE_COM
            - ROLE_ALLOWED_TO_SWITCH
    encoders:
        UserBundle\Entity\User: bcrypt

    providers:
        developpers:
            chain:
                providers: [ email ]
        email:
            entity: { class: UserBundle:User, property: email }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        todo_app:
            pattern: ^/
            provider: developpers
            anonymous: ~
            switch_user: ~
            form_login:
                login_path: user_login
                check_path: user_login_check
                username_parameter: my_login
                password_parameter: my_secret
                default_target_path: todo_homepage
                always_use_default_target_path: true
            logout:
                path: user_logout
                target: todo_homepage

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connexion$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(.+), roles: ROLE_DEV }
