<?php

namespace TodoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComplexityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplexityRepository extends EntityRepository
{
}
