<?php

namespace TodoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatRepository extends EntityRepository
{

    /**
     * Set the values of the etat Table
     * @throws \Doctrine\DBAL\DBALException
     */
    public function initEtats() {

        $conn = $this->getEntityManager()->getConnection();

        $sql = "
            INSERT INTO etat (id,nom) VALUES (1,'A faire');
            INSERT INTO etat (id,nom) VALUES (2,'En cours');
            INSERT INTO etat (id,nom) VALUES (3,'Terminé');
            INSERT INTO etat (id,nom) VALUES (4,'En attente');
        ";

        $sqls = explode(";",trim($sql));
        foreach($sqls as $insert) {

            $query = trim($insert);
            if(strlen($query)) {
                echo "Etat inserted $query \n";
                $conn->query($query);
            }

        }

    }

}
