<?php

namespace TodoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtatTacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatTacheRepository extends EntityRepository
{
}
