<?php

namespace TodoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtatTacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatTacheRepository extends EntityRepository
{

    /**
     * Return the last etat of a tache
     * @param Tache $tache
     * @return int|Etat
     */
    public function getPrevEtat(Tache $tache){

        $etat = $this->createQueryBuilder("etattache")
                ->select("etattache.etat")
                ->where("etattache.id_tache = :id_tache")
                ->orderBy("etattache.id",'DESC')
                ->getFirstResult();

        if(is_null($etat)){
            return $this->getEntityManager()
                    ->getRepository("TodoBundle:Etat")
                    ->findBy(array(
                        "nom"=>"A faire"
                    ));
        }
        return $etat;

    }

}
