user_login:
    path:     /connexion
    defaults: { _controller: UserBundle:Security:login }
    requirements:
        _method: GET
user_login_check:
    path:    /connexion
    defaults: { _controller: UserBundle:Security:loginCheck }
    requirements:
        _method: POST
user_register:
    path: /inscription
    defaults:  { _controller: UserBundle:Security:register }
    requirements:
        _method: GET|POST
