todo_homepage:
    path:     /
    defaults: { _controller: TodoBundle:Home:index }
todo_add_new_task:
    path:    /ajouter/nouvelle-tache/
    defaults: { _controller: TodoBundle:Task:new_taskPost }
    requirements:
        _method: POST
todo_add_projet:
    path: /ajouter/projet
    defaults: { _controller: TodoBundle:Projet:addProjet }
    requirements:
        _method: GET|POST
todo_create_etat:
    path:     creation-etat
    defaults: { _controller: TodoBundle:Etat:createEtat }
    requirements:
            _method: GET|POST
todo_changement_colonne:
    path:  changement-colonne/tache/{tache}/etat/{etat}
    defaults: { _controller: TodoBundle:Task:deplacementTache, tache:0,etat:"state" }
    requirements:
        tache: \d
