todo_homepage:
    path:     /
    defaults: { _controller: TodoBundle:Home:index }
#route Projet
todo_add_projet:
    path: /ajouter/projet
    defaults: { _controller: TodoBundle:Projet:addProjet }
    requirements:
        _method: GET|POST
todo_taches_projet:
    path: /projet/{projet}/afficher-les-taches
    defaults: { _controller: TodoBundle:Projet:setProjetInSession }
    requirements:
        projet: \d+
todo_change_current_project:
    path: /change-projet-courant
    defaults: { _controller: TodoBundle:Projet:changeCurrentProject }
#route Etat
todo_create_etat:
    path:     creation-etat
    defaults: { _controller: TodoBundle:Etat:createEtat }
    requirements:
            _method: GET|POST
#routes Tasks
todo_add_new_task:
    path:    /ajouter/nouvelle-tache/
    defaults: { _controller: TodoBundle:Task:new_taskPost }
    requirements:
        _method: POST
todo_changement_colonne:
    path:  changement-colonne/tache/{tache}/etat/{etat}/
    defaults: { _controller: TodoBundle:Task:deplacementTache, etat:id_etat,tache:0 }
    requirements:
        tache: \d+
todo_tache_terminee:
    path: tache-terminer/{tache}/
    defaults: { _controller: TodoBundle:Task:taskOver, tache:0 }
    requirements:
        tache: \d+
todo_tache_supprimer:
    path: supprimer-la-tache/{tache}/
    defaults: { _controller: TodoBundle:Task:delete, tache:0 }
    requirements:
        tache: \d+
todo_tache_blocked:
    path: bloquer-debloquer-tache/{tache}/
    defaults: { _controller: TodoBundle:Task:blocked, tache:0 }
    requirements:
        tache: \d+

#route Pages
todo_corbeille:
    path:     /corbeille
    defaults: { _controller: TodoBundle:Corbeille:corbeille }
todo_delete_from_corbeille:
    path:     /supprimer-tache-definitivement/{idtache}
    defaults: { _controller: TodoBundle:Corbeille:delete }
    requirements:
        _method: GET
        idtache: \d+
todo_return_from_corbeille:
    path:     /reouverture-tache/{idtache}
    defaults: { _controller: TodoBundle:Corbeille:reopen }
    requirements:
        _method: GET
        idtache: \d+

#route Statistiques
todo_statistiques_taches_terminees:
    path: /taches-terminees
    defaults: { _controller: TodoBundle:Stats:endedTask }
    requirements:
        _method: GET
todo_statistiques_projet:
    path:     /bilan-{projet}/{id_projet}
    defaults: { _controller: TodoBundle:Stats:project }

todo_statistiques_developper:
    path:     /bilan-developper/{iddev}
    defaults: { _controller: TodoBundle:Stats:developper }

#tests autoformation
todo_test:
    path: tests/
    defaults: { _controller: TodoBundle:Test:index }
todo_users:
    type: rest
    resource: TodoBundle\Controller\UsersController
