services:
#    todo.example:
#        class: TodoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    todo.handle_projet:
        class: TodoBundle\Service\Projet
        arguments:
            - "@doctrine.orm.entity_manager"

    todo.handle_tache:
        class: TodoBundle\Service\Tache
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
    todo.user_register:
        class: TodoBundle\Service\RegisterUser
        arguments:
            - '@security.secure_random'
            - '@security.password_encoder'
            - '@doctrine.orm.entity_manager'
    todo.front_functions:
        class: TodoBundle\Service\Front
        tags:
            - { name: twig.extension }
    todo.handle_etat:
        class: TodoBundle\Service\Etat
        arguments:
            - '@doctrine.orm.entity_manager'