services:
    todo.handle_projet:
        class: TodoBundle\Service\Projet
        arguments:
            - "@doctrine.orm.entity_manager"

    todo.handle_tache:
        class: TodoBundle\Service\Tache
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
    todo.user_register:
        class: TodoBundle\Service\RegisterUser
        arguments:
            - '@security.secure_random'
            - '@security.password_encoder'
            - '@doctrine.orm.entity_manager'
    todo.front_functions:
        class: TodoBundle\Service\Front
        tags:
            - { name: twig.extension }
    todo.handle_etat:
        class: TodoBundle\Service\Etat
        arguments:
            - '@doctrine.orm.entity_manager'
    todo_stats:
        class: TodoBundle\Service\Stats
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@service_container'
    todo_corbeille:
        class: TodoBundle\Service\Corbeille
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@service_container'