services:
#    todo.example:
#        class: TodoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    todo.handle_projet:
        class: TodoBundle\Service\Projet
        arguments:
            - "@doctrine.orm.entity_manager"
